export const SAVE_QUERY_DATA = 'SAVE_QUERY_DATA';
export const SAVE_QUERY_STRING = 'SAVE_QUERY_STRING';
export const REQUEST_PENDING = 'REQUEST_PENDING';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';